### ISSUE TITLE
evaluation episodes on single task setting

### ISSUE THREAD

**Issue by emrecanacikgoz** [ezhang7423/language-control-diffusion#3]
## Checklist

- [ x ] I've searched the project's [`issues`](https://github.com/ezhang7423/language-control-diffusion/issues?q=is%3Aissue).

## ❓ Question

Hi Ezhang, 

I would like to learn which episodes (i.e. rollouts, not the calvin episodes with 12 or 24 hours) you evaluate your model and HULC on single-task benchmark. I mean, could you share the start-ids and end-ids of these evaluation rollout windows?

**Comment by ezhang7423** [comment]
Hi! For the start-ids and end-ids of the single-task evaluation evaluation, we use the long-horizon rollout evaluation script here: https://github.com/ezhang7423/hulc-baseline/blob/main/hulc/evaluation/evaluate_policy.py
